import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./provider"
import ThemeSwitcher from "./ThemeSwitcher"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Magic-Aceternity",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['/apple-touch-icon.png?v=4'],
    shortcut: ['/apple-touch-icon.png']
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeSwitcher />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
